### ISSUE TITLE
getting db error while running your code project

### ISSUE THREAD

**Issue by Engbilal** [kirilkirkov/Ecommerce-Laravel-Bootstrap#14]
SQLSTATE[HY000] [1045] Access denied for user 'forge'@'localhost' (using password: NO) (SQL: select * from information_schema.tables where table_schema = forge and table_name = migrations and table_type = 'BASE TABLE')

**Comment by kirilkirkov** [comment]
@Engbilal 
Rewrite env.example to .env and add your database credentials:

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=laravel
DB_USERNAME=root
DB_PASSWORD=

**Comment by Engbilal** [comment]
okay but its not working

**Comment by Engbilal** [comment]
do you have any desk?
