### ISSUE TITLE
db issue

### ISSUE THREAD

**Issue by Engbilal** [kirilkirkov/Ecommerce-Laravel-Bootstrap#15]
Illuminate\Database\QueryException 

  2   C:\xampp\htdocs\Ecommerce-Laravel-Bootstrap-master\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:44
      Doctrine\DBAL\Driver\PDO\Exception::new(Object(PDOException))

**Comment by kirilkirkov** [comment]
@Engbilal  
Ensure the database server is running and you credentials are ok
