### ISSUE TITLE
your code does not work

### ISSUE THREAD

**Issue by Engbilal** [kirilkirkov/Ecommerce-Laravel-Bootstrap#16]
500
Server Error

**Comment by kirilkirkov** [comment]
@Engbilal 
Are you sure that your APP_DEBUG is true ? Paste me here the error and i will provide you solution

**Comment by Engbilal** [comment]
[Thu Jun  8 21:39:39 2023] PHP 8.0.28 Development Server (http://127.0.0.1:8000) started
[Thu Jun  8 21:39:47 2023] 127.0.0.1:51900 Accepted
[Thu Jun  8 21:39:48 2023] 127.0.0.1:51900 Closing
[Thu Jun  8 21:39:48 2023] 127.0.0.1:51904 Accepted
[Thu Jun  8 21:40:32 2023] 127.0.0.1:51904 Closed without sending a request; it was probably just an unused speculative preconnection
[Thu Jun  8 21:40:32 2023] 127.0.0.1:51904 Closing

**Comment by Engbilal** [comment]
![image](https://github.com/kirilkirkov/Ecommerce-Laravel-Bootstrap/assets/53390747/a81b6350-bb52-417b-9291-c8105b5380bb)

**Comment by kirilkirkov** [comment]
you should create apache/nginx virtual host and point it to public directory of the project
