### ISSUE TITLE
data base is incomplete. missing some columns in it

### ISSUE THREAD

**Issue by Engbilal** [kirilkirkov/Ecommerce-Laravel-Bootstrap#17]
Hey i run your project but the column is in complete in it.

**Comment by Engbilal** [comment]
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tags' in 'field list' (SQL: insert into `products` (`image`, `folder`, `category_id`, `quantity`, `order_position`, `link_to`, `tags`, `hidden`, `url`) values (images/lgMVdzyK22dMzC7DagJIDCOrGkVhtH49NMFG9iHK.png, 1686384732, 2, 21, 12, HTTPS://WWW.COM, 2, 1, aSADASDASD-2))

**Comment by Engbilal** [comment]
can you provide the database again ?

**Comment by Engbilal** [comment]
after adding column in the database. i got the error 

SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'tags' in where clause is ambiguous (SQL: select products.*, products_translations.name, products_translations.description, products_translations.price from `products` inner join `products_translations` on `products_translations`.`for_id` = `products`.`id` where `tags` LIKE %promo% and `hidden` = 0 and `locale` = en limit 8)

**Comment by dassudip2001** [comment]
can i fix it

**Comment by kirilkirkov** [comment]
@dassudip2001 
you are welcome to make a pull request with the fix

**Comment by dassudip2001** [comment]
Package fruitcake/laravel-cors is abandoned, you should avoid using it. No replacement was suggested.
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.

some package are abandoned

**Comment by kirilkirkov** [comment]
@Engbilal 
@dassudip2001 

Into the **2022_11_07_075654_create_products_table.php** file , the **tags** column is present so i am not sure why you do not have it.
I have tested everything and it works. Please run your migrations from "zero" and try again, the tags field present into the migrations so it working.

With version php@8.0 is working ok.

**Comment by kirilkirkov** [comment]
@Engbilal 
in which page you are getting this error? i can not reproduce it

**Comment by dassudip2001** [comment]
@kirilkirkov ok

**Comment by kirilkirkov** [comment]
@Engbilal 
if you need further assistance i am available
