### ISSUE TITLE
Images are not showing at frontend

### ISSUE THREAD

**Issue by programmer11111** [kirilkirkov/Ecommerce-Laravel-Bootstrap#8]
What am I trying to do.. ..then in products and also in carousel images are not showing

https://ibb.co/JrqHKBd

https://ibb.co/H7WV6NS

**Comment by kirilkirkov** [comment]
@programmer11111  Do you have permissions? Check is ok the path of image

**Comment by kirilkirkov** [comment]
Its fixed
